### ISSUE TITLE
Content not avalible

### ISSUE THREAD

**Issue by kreativkombinat** [a25kk/sing#1]
Seit den letzten Update geht /edit für die contentseiten nicht, wird einfach gar kein content dargestellt. Hab schon versucht lokal zu debuggen, komme leider nicht weiter. Kannst du bitte nachschauen was das sein kann?

**Comment by potzenheimer** [comment]
Nicht ausgeführter Migration Step im Gs Profile von *plone.app.contenttypes* war ursächlich für den Fehler verantwortlich.
